name: Bug report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug and what you expected instead.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal code/steps to reproduce. Include settings.py relevant config (redact secrets).
      render: python
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: django-snippe version
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    id: django-version
    attributes:
      label: Django version
      placeholder: "5.1"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / traceback
      render: shell
